export const  FROM_SERVICE_INIT = 'FROM_SERVICE_INIT_DATA'; //
export const  FROM_WEBHOOK_CONFIG_INIT = 'FROM_WEBHOOK_CONFIG_INIT_DATA'; // WEBHOOK
export const  MODAL_FORM = 'MODAL_FORM_FIELD_VAL'; // 字modal form
